# ## path: docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    container_name: task_sync_app
    env_file:
      - .env
    volumes:
      # Mount the credentials file into the container
      - ./client_secret.json:/app/client_secret.json
      # Mount a volume to persist user auth tokens across container restarts
      - token_cache:/app/token_cache
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - task_network

  db:
    image: postgres:14-alpine
    container_name: task_sync_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      # Optional: Expose port 5432 to host for debugging
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - task_network

volumes:
  postgres_data:
  token_cache:

networks:
  task_network:
    driver: bridge